/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlannerIndexRouteImport } from './routes/planner/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as FamiliesIndexRouteImport } from './routes/families/index'
import { Route as PlannerWeekRouteImport } from './routes/planner/$week'
import { Route as GroupsNewRouteImport } from './routes/groups/new'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as FamiliesNewRouteImport } from './routes/families/new'
import { Route as FamiliesFamilyIdRouteImport } from './routes/families/$familyId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerIndexRoute = PlannerIndexRouteImport.update({
  id: '/planner/',
  path: '/planner/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIndexRoute = FamiliesIndexRouteImport.update({
  id: '/families/',
  path: '/families/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerWeekRoute = PlannerWeekRouteImport.update({
  id: '/planner/$week',
  path: '/planner/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesNewRoute = FamiliesNewRouteImport.update({
  id: '/families/new',
  path: '/families/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesFamilyIdRoute = FamiliesFamilyIdRouteImport.update({
  id: '/families/$familyId',
  path: '/families/$familyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/families/new': typeof FamiliesNewRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/new': typeof GroupsNewRoute
  '/planner/$week': typeof PlannerWeekRoute
  '/families/': typeof FamiliesIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/planner/': typeof PlannerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/families/new': typeof FamiliesNewRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/new': typeof GroupsNewRoute
  '/planner/$week': typeof PlannerWeekRoute
  '/families': typeof FamiliesIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/planner': typeof PlannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/families/new': typeof FamiliesNewRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/new': typeof GroupsNewRoute
  '/planner/$week': typeof PlannerWeekRoute
  '/families/': typeof FamiliesIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/planner/': typeof PlannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/links'
    | '/login'
    | '/register'
    | '/settings'
    | '/families/$familyId'
    | '/families/new'
    | '/groups/$groupId'
    | '/groups/new'
    | '/planner/$week'
    | '/families/'
    | '/groups/'
    | '/planner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/links'
    | '/login'
    | '/register'
    | '/settings'
    | '/families/$familyId'
    | '/families/new'
    | '/groups/$groupId'
    | '/groups/new'
    | '/planner/$week'
    | '/families'
    | '/groups'
    | '/planner'
  id:
    | '__root__'
    | '/'
    | '/links'
    | '/login'
    | '/register'
    | '/settings'
    | '/families/$familyId'
    | '/families/new'
    | '/groups/$groupId'
    | '/groups/new'
    | '/planner/$week'
    | '/families/'
    | '/groups/'
    | '/planner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  FamiliesFamilyIdRoute: typeof FamiliesFamilyIdRoute
  FamiliesNewRoute: typeof FamiliesNewRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsNewRoute: typeof GroupsNewRoute
  PlannerWeekRoute: typeof PlannerWeekRoute
  FamiliesIndexRoute: typeof FamiliesIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  PlannerIndexRoute: typeof PlannerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/': {
      id: '/planner/'
      path: '/planner'
      fullPath: '/planner/'
      preLoaderRoute: typeof PlannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/': {
      id: '/families/'
      path: '/families'
      fullPath: '/families/'
      preLoaderRoute: typeof FamiliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/$week': {
      id: '/planner/$week'
      path: '/planner/$week'
      fullPath: '/planner/$week'
      preLoaderRoute: typeof PlannerWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/new': {
      id: '/families/new'
      path: '/families/new'
      fullPath: '/families/new'
      preLoaderRoute: typeof FamiliesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$familyId': {
      id: '/families/$familyId'
      path: '/families/$familyId'
      fullPath: '/families/$familyId'
      preLoaderRoute: typeof FamiliesFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  FamiliesFamilyIdRoute: FamiliesFamilyIdRoute,
  FamiliesNewRoute: FamiliesNewRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsNewRoute: GroupsNewRoute,
  PlannerWeekRoute: PlannerWeekRoute,
  FamiliesIndexRoute: FamiliesIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  PlannerIndexRoute: PlannerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
